export const Routes = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: (slug: string) => `/products/${slug}`,
  COLLECTIONS: '/collections',
  COLLECTION_DETAIL: (slug: string) => `/collections/${slug}`,
  CART: '/cart',
  WISHLIST: '/wishlist',
  SEARCH: '/search',
  JOURNAL: '/journal',
  ABOUT: '/about',
  CONTACT: '/contact',
  ACCOUNT: '/account/dashboard',
  ORDERS: '/account/orders',
  PROFILE: '/account/profile',
  LOGIN: '/login',
  REGISTER: '/register',
  PRIVACY: '/privacy-policy',
  TERMS: '/terms',
  FAQ: '/faq',
} as const;
