import { Product } from "./types";
import { productsData as rawProducts } from "@/data/products";

export const dummyProducts: Product[] = rawProducts.map((p) => ({
  id: p.id,
  sku: p.sku || `SKU-${p.id}`,
  parentSku: p.parentSku || p.sku || `PARENT-${p.id}`,
  name: p.name,
  slug: p.slug,
  categoryId: p.categoryId,
  category: p.category,
  collectionId: p.collectionId,
  collection: p.collection,
  type: p.type,
  fabric: p.fabric,
  color: p.color,
  basePrice: p.basePrice ?? p.price ?? 0,
  price: p.price ?? p.basePrice ?? 0,
  compareAtPrice: p.compareAtPrice,
  offlineBazaarPrice: p.offlineBazaarPrice,
  currency: p.currency || "IDR",
  description: p.description,
  story: p.story || "Part of the signature AISCHMIRA collection.",
  material: p.material || (p.fabric ? `${p.fabric} fabrication` : "Artisanal luxury textile"),
  careInstruction: p.careInstruction || "Dry clean only. Iron on low silk setting.",
  shippingInfo: p.shippingInfo || "Complimentary express shipping across Indonesia.",
  variants: p.variants.map((v) => ({
    id: v.id,
    sku: v.sku,
    skuNo: v.skuNo,
    skuCode: v.skuCode,
    skuName: v.skuName,
    color: v.color,
    size: v.size,
    price: v.price,
    compareAtPrice: v.compareAtPrice,
    offlineBazaarPrice: v.offlineBazaarPrice,
    stock: v.stock,
    images: v.images || p.images,
  })),
  images: p.images,
  relatedProductIds: p.relatedProductIds || [],
  status: p.status || "active",
  isActive: p.isActive !== undefined ? p.isActive : true,
  isFeatured: p.isFeatured || false,
  createdAt: p.createdAt || "2026-07-01T00:00:00Z",
  updatedAt: p.updatedAt || "2026-08-20T00:00:00Z",
}));
